<?php

namespace Database\Factories;

use Illuminate\Database\Eloquent\Factories\Factory;
use Illuminate\Support\Str;
use App\Models\credit;

class CreditFactory extends Factory
{
    /**
     * The name of the factory's corresponding model.
     *
     * @var string
     */
    protected $model = Credit::class;

    /**
     * Define the model's default state.
     *
     * @return array
     */
    public function definition()
    {
        return [
            'STATUS_REC' => $this->faker->word,
            'STATUS_DATA' => $this->faker->word,
            'AREA' => $this->faker->word,
            'BRANCH' => $this->faker->word,
            'CUST_CODE' => $this->faker->word,
            'FAC_TYPE' => $this->faker->word,
            'FAC_SEC_NUM' => $this->faker->word,
            'CUST_NO_FAC' => $this->faker->word,
            'FAC_SEQ_FAC' => $this->faker->word,
            'LOAN_CUST_NO' => $this->faker->word,
            'CUST_PARENT_NO' => $this->faker->word,
            'LOAN_NUMBER' => $this->faker->word,
            'LOAN_PROCESS' => $this->faker->word,
            'LOAN_TYPE' => $this->faker->word,
            'LOAN_CURR_CODE' => $this->faker->word,
            'LOAN_HOLDER' => $this->faker->word,
            'TANGIBLE_FLAG' => $this->faker->word,
            'ALTERNATE' => $this->faker->word,
            'ECO_SECTOR_CODE' => $this->faker->word,
            'INDUSTRY_CODE' => $this->faker->word,
            'lOCATION_CODE' => $this->faker->word,
            'TYPE_OF_USE' => $this->faker->word,
            'CLCT_EXTERNAL' => $this->faker->word,
            'CLCT_INTERNAL' => $this->faker->word,
            'CLCT_SYSTEM' => $this->faker->word,
            'OWNER_CLASS' => $this->faker->word,
            'AO_CODE' => $this->faker->word,
            'NARRATIVE' => $this->faker->word,
            'START_DATE' => $this->faker->date(),
            'DATE' => $this->faker->date(),
            'START_AREA_CODE' => $this->faker->word,
            'BRANCH_CODE_START' => $this->faker->word,
            'KUK_FLG' => $this->faker->word,
            'STOP_INT_FLG' => $this->faker->word,
            'STOP_PLTY_ACCR' => $this->faker->word,
            'WRITE_OFF' => $this->faker->word,
            'DURATION' => $this->faker->word,
            'CALC_METH' => $this->faker->word,
            'BASE_RATE_CODE' => $this->faker->word,
            'SPREAD_PER_RATE' => $this->faker->randomFloat(2, 0, 999999999999999999.99),
            'INT_RATE' => $this->faker->randomFloat(2, 0, 999999999999999999.99),
            'DUMMY_INT_RATE' => $this->faker->randomFloat(2, 0, 999999999999999999.99),
            'INT_RATE_ADV' => $this->faker->randomFloat(2, 0, 999999999999999999.99),
            'MARGIN_RATE' => $this->faker->randomFloat(2, 0, 999999999999999999.99),
            'MARGIN_INDICATOR' => $this->faker->word,
            'LOAN_EXCH_RATE' => $this->faker->randomFloat(2, 0, 999999999999999999.99),
            'FAC_EXCH_RATE' => $this->faker->randomFloat(2, 0, 999999999999999999.99),
            'FACILITY_AMT_ORI' => $this->faker->randomFloat(2, 0, 999999999999999999.99),
            'DWN_START_STTL_AC' => $this->faker->word,
            'RPY_PCPL_STTL_AC' => $this->faker->word,
            'INT_SETTLE_AC' => $this->faker->word,
            'REPAY_AUTO_FLAG' => $this->faker->word,
            'INT_AUTO_FLAG' => $this->faker->word,
            'REPAY_TYPE' => $this->faker->word,
            'REPAY_DATE' => $this->faker->date(),
            'FREQUENCY' => $this->faker->word,
            'REPAY_DAY_NO' => $this->faker->word,
            'REPAY_VAL' => $this->faker->randomFloat(2, 0, 999999999999999999.99),
            'START_PRC_DEDUCT' => $this->faker->randomFloat(2, 0, 999999999999999999.99),
            'NEXT_REPAY_DATE' => $this->faker->date(),
            'LAST_REPAY_DATE' => $this->faker->date(),
            'REPAY_SCHED_FLG' => $this->faker->word,
            'INT_PAY_DATE' => $this->faker->date(),
            'INT_PAY_FREQ' => $this->faker->word,
            'INT_PAY_DAY_NO' => $this->faker->word,
            'INTEREST' => $this->faker->randomFloat(2, 0, 999999999999999999.99),
            'NEXT_INT_PAY' => $this->faker->date(),
            'LAST_INT_PAY' => $this->faker->date(),
            'INT_PAY_REV_FLG' => $this->faker->word,
            'PENALTY_RATE' => $this->faker->randomFloat(2, 0, 999.99),
            'MIN_PENALTY' => $this->faker->randomFloat(2, 0, 999999999999999999.99),
            'PCPL_ORI' => $this->faker->randomFloat(2, 0, 999999999999999999.99),
            'TOT_INT_DISC' => $this->faker->randomFloat(2, 0, 999999999999999999.99),
            'INT_BACK_DATE' => $this->faker->date(),
            'PCPL_BACK_DATE' => $this->faker->date(),
            'ACCRUAL_DIV_FACTOR' => $this->faker->word,
            'STOP_INT_ACC' => $this->faker->word,
            'ACCRUE_ADJ_MANUAL' => $this->faker->word,
            'ACCRUE_ADJ_SYS' => $this->faker->word,
            'LAST_ACCRUED' => $this->faker->date(),
            'NEXT_POST_ORG_CURR' => $this->faker->word,
            'LAST_ACC_POST' => $this->faker->date(),
            'NEXT_CAP_ORG_CURR' => $this->faker->word,
            'LAST_CAPITALIZED' => $this->faker->date(),
            'TOT_CAP_ORG_CURR' => $this->faker->randomFloat(2, 0, 999999999999999999.99),
            'ACCRUAL_DYS_COUNT' => $this->faker->word,
            'DUE_PRINCIPLE' => $this->faker->randomFloat(2, 0, 999999999999999999.99),
            'DUE_INTEREST' => $this->faker->randomFloat(2, 0, 999999999999999999.99),
            'DUE_PENALTY' => $this->faker->randomFloat(2, 0, 999999999999999999.99),
            'PRINCIPLE_PAID' => $this->faker->randomFloat(2, 0, 999999999999999999.99),
            'INTEREST_PAID' => $this->faker->randomFloat(2, 0, 999999999999999999.99),
            'PENALTY_PAID' => $this->faker->randomFloat(2, 0, 999999999999999999.99),
            'FEE_PAID' => $this->faker->randomFloat(2, 0, 999999999999999999.99),
            'PRINCIPLE_WOFF' => $this->faker->randomFloat(2, 0, 999999999999999999.99),
            'INTEREST_WOFF' => $this->faker->randomFloat(2, 0, 999999999999999999.99),
            'PENALTY_WOFF' => $this->faker->randomFloat(2, 0, 999999999999999999.99),
            'UNAUTH_PCPL_PAID' => $this->faker->randomFloat(2, 0, 999999999999999999.99),
            'UNAUTH_INTRST_PAID' => $this->faker->randomFloat(2, 0, 999999999999999999.99),
            'UNAUTH_PENALTY_PAID' => $this->faker->randomFloat(2, 0, 999999999999999999.99),
            'UNAUTH_FEE_PAID' => $this->faker->randomFloat(2, 0, 999999999999999999.99),
            'PCPL_UNAUTH_WRT_OFF' => $this->faker->randomFloat(2, 0, 999999999999999999.99),
            'INTRST_UNAUTH_WRT_OFF' => $this->faker->randomFloat(2, 0, 999999999999999999.99),
            'PLTY_UNAUTH_WRT_OFF' => $this->faker->randomFloat(2, 0, 999999999999999999.99),
            'REPAY_DUE_DATE' => $this->faker->date(),
            'START_INTEREST_DUE' => $this->faker->date(),
            'LAST_PRINCIPLE_PAY' => $this->faker->date(),
            'LAST_INTEREST_PAY' => $this->faker->date(),
            'LAST_PENALTY_PAY' => $this->faker->date(),
            'LAST_FEE_PAY' => $this->faker->date(),
            'LAST_WRITE_PCPL' => $this->faker->date(),
            'LAST_WRITE_INT' => $this->faker->date(),
            'START_PENALTY' => $this->faker->date(),
            'LAST_WRITE_OFF' => $this->faker->date(),
            'PENALTY_NUMBER' => $this->faker->word,
            'OVERRIDE_FLAG' => $this->faker->word,
            'OVERRIDE_BY' => $this->faker->word,
            'FIRST_JOB_ENT' => $this->faker->date(),
            'USER_ID' => $this->faker->word,
            'DEPT_CODE' => $this->faker->word,
            'LAST_SYS_AMEND' => $this->faker->date(),
            'LAST_JOB_AMEND' => $this->faker->date(),
            'LAST_AMEND' => $this->faker->word,
            'AUTH_BY' => $this->faker->word,
            'DISP_ID' => $this->faker->word,
            'SID_CODE' => $this->faker->word,
            'SOURCE_FUND' => $this->faker->word,
        ];
    }
}
