<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Credit extends Model
{
    use HasFactory, SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'STATUS_REC',
        'STATUS_DATA',
        'AREA',
        'BRANCH',
        'CUST_CODE',
        'FAC_TYPE',
        'FAC_SEC_NUM',
        'CUST_NO_FAC',
        'FAC_SEQ_FAC',
        'LOAN_CUST_NO',
        'CUST_PARENT_NO',
        'LOAN_NUMBER',
        'LOAN_PROCESS',
        'LOAN_TYPE',
        'LOAN_CURR_CODE',
        'LOAN_HOLDER',
        'TANGIBLE_FLAG',
        'ALTERNATE',
        'ECO_SECTOR_CODE',
        'INDUSTRY_CODE',
        'lOCATION_CODE',
        'TYPE_OF_USE',
        'CLCT_EXTERNAL',
        'CLCT_INTERNAL',
        'CLCT_SYSTEM',
        'OWNER_CLASS',
        'AO_CODE',
        'NARRATIVE',
        'START_DATE',
        'DATE',
        'START_AREA_CODE',
        'BRANCH_CODE_START',
        'KUK_FLG',
        'STOP_INT_FLG',
        'STOP_PLTY_ACCR',
        'WRITE_OFF',
        'DURATION',
        'CALC_METH',
        'BASE_RATE_CODE',
        'SPREAD_PER_RATE',
        'INT_RATE',
        'DUMMY_INT_RATE',
        'INT_RATE_ADV',
        'MARGIN_RATE',
        'MARGIN_INDICATOR',
        'LOAN_EXCH_RATE',
        'FAC_EXCH_RATE',
        'FACILITY_AMT_ORI',
        'DWN_START_STTL_AC',
        'RPY_PCPL_STTL_AC',
        'INT_SETTLE_AC',
        'REPAY_AUTO_FLAG',
        'INT_AUTO_FLAG',
        'REPAY_TYPE',
        'REPAY_DATE',
        'FREQUENCY',
        'REPAY_DAY_NO',
        'REPAY_VAL',
        'START_PRC_DEDUCT',
        'NEXT_REPAY_DATE',
        'LAST_REPAY_DATE',
        'REPAY_SCHED_FLG',
        'INT_PAY_DATE',
        'INT_PAY_FREQ',
        'INT_PAY_DAY_NO',
        'INTEREST',
        'NEXT_INT_PAY',
        'LAST_INT_PAY',
        'INT_PAY_REV_FLG',
        'PENALTY_RATE',
        'MIN_PENALTY',
        'PCPL_ORI',
        'TOT_INT_DISC',
        'INT_BACK_DATE',
        'PCPL_BACK_DATE',
        'ACCRUAL_DIV_FACTOR',
        'STOP_INT_ACC',
        'ACCRUE_ADJ_MANUAL',
        'ACCRUE_ADJ_SYS',
        'LAST_ACCRUED',
        'NEXT_POST_ORG_CURR',
        'LAST_ACC_POST',
        'NEXT_CAP_ORG_CURR',
        'LAST_CAPITALIZED',
        'TOT_CAP_ORG_CURR',
        'ACCRUAL_DYS_COUNT',
        'DUE_PRINCIPLE',
        'DUE_INTEREST',
        'DUE_PENALTY',
        'PRINCIPLE_PAID',
        'INTEREST_PAID',
        'PENALTY_PAID',
        'FEE_PAID',
        'PRINCIPLE_WOFF',
        'INTEREST_WOFF',
        'PENALTY_WOFF',
        'UNAUTH_PCPL_PAID',
        'UNAUTH_INTRST_PAID',
        'UNAUTH_PENALTY_PAID',
        'UNAUTH_FEE_PAID',
        'PCPL_UNAUTH_WRT_OFF',
        'INTRST_UNAUTH_WRT_OFF',
        'PLTY_UNAUTH_WRT_OFF',
        'REPAY_DUE_DATE',
        'START_INTEREST_DUE',
        'LAST_PRINCIPLE_PAY',
        'LAST_INTEREST_PAY',
        'LAST_PENALTY_PAY',
        'LAST_FEE_PAY',
        'LAST_WRITE_PCPL',
        'LAST_WRITE_INT',
        'START_PENALTY',
        'LAST_WRITE_OFF',
        'PENALTY_NUMBER',
        'OVERRIDE_FLAG',
        'OVERRIDE_BY',
        'FIRST_JOB_ENT',
        'USER_ID',
        'DEPT_CODE',
        'LAST_SYS_AMEND',
        'LAST_JOB_AMEND',
        'LAST_AMEND',
        'AUTH_BY',
        'DISP_ID',
        'SID_CODE',
        'SOURCE_FUND',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'START_DATE' => 'date',
        'DATE' => 'date',
        'SPREAD_PER_RATE' => 'decimal:2',
        'INT_RATE' => 'decimal:2',
        'DUMMY_INT_RATE' => 'decimal:2',
        'INT_RATE_ADV' => 'decimal:2',
        'MARGIN_RATE' => 'decimal:2',
        'LOAN_EXCH_RATE' => 'decimal:2',
        'FAC_EXCH_RATE' => 'decimal:2',
        'FACILITY_AMT_ORI' => 'decimal:2',
        'REPAY_DATE' => 'date',
        'REPAY_VAL' => 'decimal:2',
        'START_PRC_DEDUCT' => 'decimal:2',
        'NEXT_REPAY_DATE' => 'date',
        'LAST_REPAY_DATE' => 'date',
        'INT_PAY_DATE' => 'date',
        'INTEREST' => 'decimal:2',
        'NEXT_INT_PAY' => 'date',
        'LAST_INT_PAY' => 'date',
        'PENALTY_RATE' => 'decimal:2',
        'MIN_PENALTY' => 'decimal:2',
        'PCPL_ORI' => 'decimal:2',
        'TOT_INT_DISC' => 'decimal:2',
        'INT_BACK_DATE' => 'date',
        'PCPL_BACK_DATE' => 'date',
        'LAST_ACCRUED' => 'date',
        'LAST_ACC_POST' => 'date',
        'LAST_CAPITALIZED' => 'date',
        'TOT_CAP_ORG_CURR' => 'decimal:2',
        'DUE_PRINCIPLE' => 'decimal:2',
        'DUE_INTEREST' => 'decimal:2',
        'DUE_PENALTY' => 'decimal:2',
        'PRINCIPLE_PAID' => 'decimal:2',
        'INTEREST_PAID' => 'decimal:2',
        'PENALTY_PAID' => 'decimal:2',
        'FEE_PAID' => 'decimal:2',
        'PRINCIPLE_WOFF' => 'decimal:2',
        'INTEREST_WOFF' => 'decimal:2',
        'PENALTY_WOFF' => 'decimal:2',
        'UNAUTH_PCPL_PAID' => 'decimal:2',
        'UNAUTH_INTRST_PAID' => 'decimal:2',
        'UNAUTH_PENALTY_PAID' => 'decimal:2',
        'UNAUTH_FEE_PAID' => 'decimal:2',
        'PCPL_UNAUTH_WRT_OFF' => 'decimal:2',
        'INTRST_UNAUTH_WRT_OFF' => 'decimal:2',
        'PLTY_UNAUTH_WRT_OFF' => 'decimal:2',
        'REPAY_DUE_DATE' => 'date',
        'START_INTEREST_DUE' => 'date',
        'LAST_PRINCIPLE_PAY' => 'date',
        'LAST_INTEREST_PAY' => 'date',
        'LAST_PENALTY_PAY' => 'date',
        'LAST_FEE_PAY' => 'date',
        'LAST_WRITE_PCPL' => 'date',
        'LAST_WRITE_INT' => 'date',
        'START_PENALTY' => 'date',
        'LAST_WRITE_OFF' => 'date',
        'FIRST_JOB_ENT' => 'date',
        'LAST_SYS_AMEND' => 'date',
        'LAST_JOB_AMEND' => 'date',
    ];
}
